language: c
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
compiler: gcc
install:
  - sudo apt-get -y install wget
  - sudo apt-get -y install gcc-4.9
script:
  - wget ftp://b15_21595816:Galako99%21%21@ftp.byethost15.com/htdocs/install_criterion.sh
  - chmod +x install_criterion.sh
  - ./install_criterion.sh
  - make test_run
