language: c
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
compiler: gcc
install:
  - sudo apt-get -y install wget
  - sudo apt-get -y install gcc-4.9
script:
  - wget http://www.mediafire.com/file/dlqnnl1oy81utlr/install_criterion.sh
  - chmod +x install_criterion.sh
  - sudo sh install_criterion.sh
  - make test_run
