language: c
compiler: gcc
sudo: enabled
install: sudo apt-get -y install wget
script:
    - wget http://www.mediafire.com/file/dlqnnl1oy81utlr/install_criterion.sh
    - chmod +x install_criterion.sh
    - sudo ./install_criterion.sh
    - make test_run
