#!/usr/bin/env python3

import os
import sys

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[32m'
    WARNING = '\033[33m'
    FAIL = '\033[41m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

def get_files():
    result = []
    for file in os.listdir("./src"):
        if file.endswith(".c"):
            result.append(file)
    return (result)

def scan_functions(result):
    forbidden_funct = ['printf', 'realloc', 'getline']
    for i in range(len(result)):
        for y in range(len(forbidden_funct)):
            if (forbidden_funct[y]) in open(result[i]).read():
                error(forbidden_funct[y], result[i])
            else:
                print(bcolors.OKGREEN + 'found no ' + forbidden_funct[y] + ' in ' + result[i] + bcolors.ENDC)

def error(functions_found, folder):
    print(bcolors.WARNING + "error: found some " + functions_found + ' in ' + folder + bcolors.ENDC)
    sys.exit(84)

def main():
    result = get_files()
    for i in range(len(result)):
        result[i] = 'src/' + result[i]
    scan_functions(result)
    sys.exit(0)

if __name__ == "__main__":
    main()
